/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    services: Service;
    statistics: Statistic;
    'case-studies': CaseStudy;
    partners: Partner;
    'blog-posts': BlogPost;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    statistics: StatisticsSelect<false> | StatisticsSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ar' | 'en') | ('ar' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    footer: Footer;
    'hero-content': HeroContent;
    'homepage-settings': HomepageSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'hero-content': HeroContentSelect<false> | HeroContentSelect<true>;
    'homepage-settings': HomepageSettingsSelect<false> | HomepageSettingsSelect<true>;
  };
  locale: 'ar' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug: string;
  hero?: {
    type?: ('standard' | 'homepage' | 'none') | null;
    badge?: string | null;
    title?: string | null;
    subtitle?: string | null;
    primaryCta?: {
      label?: string | null;
      href?: string | null;
    };
    secondaryCta?: {
      label?: string | null;
      href?: string | null;
    };
    homepageHeadline?: {
      before?: string | null;
      emphasis?: string | null;
      after?: string | null;
    };
    homepageSubtitle?: string | null;
    homepagePrimaryCta?: {
      label?: string | null;
      href?: string | null;
    };
    homepageCards?:
      | {
          title: string;
          description: string;
          visual?: ('button' | 'process' | 'chart') | null;
          id?: string | null;
        }[]
      | null;
  };
  layout?:
    | (
        | {
            headline?: {
              before?: string | null;
              emphasis?: string | null;
              after?: string | null;
            };
            subtitle?: string | null;
            primaryCta?: {
              label?: string | null;
              href?: string | null;
            };
            cards?:
              | {
                  title: string;
                  description: string;
                  visual?: ('button' | 'process' | 'chart') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero-block';
          }
        | {
            sectionTag?: string | null;
            title?: string | null;
            description?: string | null;
            selectionMode?: ('all' | 'manual') | null;
            manualServices?: (string | Service)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'services-block';
          }
        | {
            sectionTag?: string | null;
            title?: string | null;
            description?: string | null;
            selectionMode?: ('featured' | 'latest' | 'manual') | null;
            manualCaseStudies?: (string | CaseStudy)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featured-work-block';
          }
        | {
            sectionTag?: string | null;
            selectionMode?: ('all' | 'featured' | 'manual') | null;
            manualPartners?: (string | Partner)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'partners-block';
          }
        | {
            sectionTag?: string | null;
            title?: string | null;
            description?: string | null;
            selectionMode?: ('latest' | 'featured' | 'manual') | null;
            manualPosts?: (string | BlogPost)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'blog-block';
          }
        | {
            sectionTag?: string | null;
            title?: string | null;
            selectionMode?: ('all' | 'manual') | null;
            manualStats?: (string | Statistic)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'statistics-block';
          }
        | {
            sectionTag?: string | null;
            title?: string | null;
            steps?:
              | {
                  title: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'methodology-block';
          }
        | {
            sectionTag?: string | null;
            title?: string | null;
            description?: string | null;
            whyCards?:
              | {
                  icon?: string | null;
                  iconMedia?: (string | null) | Media;
                  title: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            stats?:
              | {
                  value: string;
                  label: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'who-we-are-block';
          }
        | {
            headline?: string | null;
            subtitle?: string | null;
            primaryCta?: {
              label?: string | null;
              href?: string | null;
            };
            secondaryCta?: {
              label?: string | null;
              href?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'final-cta-block';
          }
        | {
            sectionTag?: string | null;
            title?: string | null;
            description?: string | null;
            cta?: {
              label?: string | null;
              href?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'about-hero-block';
          }
        | {
            sectionTag?: string | null;
            title?: string | null;
            description?: string | null;
            /**
             * Upload or select the story section image.
             */
            image?: (string | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'about-story-block';
          }
        | {
            cards?:
              | {
                  title: string;
                  description: string;
                  bgType: 'lavender' | 'navy' | 'orange' | 'light-orange';
                  icon: 'target' | 'eye' | 'medal' | 'layer';
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'about-values-block';
          }
        | {
            sectionTag?: string | null;
            title?: string | null;
            items?:
              | {
                  name: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'solutions-block';
          }
        | {
            sectionTag?: string | null;
            title?: string | null;
            sectors?:
              | {
                  name: string;
                  image?: (string | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'sectors-block';
          }
      )[]
    | null;
  seo?: {
    /**
     * Title shown in search engine results and browser tabs. Recommended: 50-60 characters.
     */
    metaTitle?: string | null;
    /**
     * Description shown in search engine results. Recommended: 150-160 characters.
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords for SEO.
     */
    keywords?: string | null;
    /**
     * Title for social media sharing. Falls back to Meta Title if empty.
     */
    ogTitle?: string | null;
    ogType?: ('website' | 'article') | null;
    /**
     * Description for social media sharing. Falls back to Meta Description if empty.
     */
    ogDescription?: string | null;
    /**
     * Image shown when shared on social media. Recommended: 1200×630px.
     */
    ogImage?: (string | null) | Media;
    twitterCard?: ('summary' | 'summary_large_image') | null;
    /**
     * Set a custom canonical URL if this content is duplicated from another page.
     */
    canonicalUrl?: string | null;
    /**
     * Prevent search engines from indexing this page.
     */
    noIndex?: boolean | null;
    /**
     * Prevent search engines from following links on this page.
     */
    noFollow?: boolean | null;
    /**
     * Optional schema.org JSON-LD structured data for rich search results.
     */
    structuredData?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  settings?: {
    transparentHeader?: boolean | null;
    pageTemplate?: ('default' | 'landing' | 'fullWidth') | null;
    breadcrumbVisibility?: boolean | null;
    defaultTheme?: ('light' | 'dark' | 'auto') | null;
    animationToggle?: boolean | null;
    previewImage?: (string | null) | Media;
    analyticsIdentifiers?: {
      gtmId?: string | null;
      conversionTag?: string | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  title: string;
  description: string;
  /**
   * Main image displayed on the service card.
   */
  image?: (string | null) | Media;
  seo?: {
    /**
     * Title shown in search engine results and browser tabs. Recommended: 50-60 characters.
     */
    metaTitle?: string | null;
    /**
     * Description shown in search engine results. Recommended: 150-160 characters.
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords for SEO.
     */
    keywords?: string | null;
    /**
     * Title for social media sharing. Falls back to Meta Title if empty.
     */
    ogTitle?: string | null;
    ogType?: ('website' | 'article') | null;
    /**
     * Description for social media sharing. Falls back to Meta Description if empty.
     */
    ogDescription?: string | null;
    /**
     * Image shown when shared on social media. Recommended: 1200×630px.
     */
    ogImage?: (string | null) | Media;
    twitterCard?: ('summary' | 'summary_large_image') | null;
    /**
     * Set a custom canonical URL if this content is duplicated from another page.
     */
    canonicalUrl?: string | null;
    /**
     * Prevent search engines from indexing this page.
     */
    noIndex?: boolean | null;
    /**
     * Prevent search engines from following links on this page.
     */
    noFollow?: boolean | null;
    /**
     * Optional schema.org JSON-LD structured data for rich search results.
     */
    structuredData?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  /**
   * Auto-generated from title. Edit to customize.
   */
  slug?: string | null;
  /**
   * AI Card spans 2 cols, Globe Card spans full width.
   */
  layout: 'ai-card' | 'globe-card' | 'standard';
  /**
   * Lower numbers appear first.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: string;
  title: string;
  category: string;
  /**
   * Choose whether to display a static image or a live website preview (iframe) for this project.
   */
  displayMode: 'image' | 'livePreview';
  /**
   * Upload or select a project image.
   */
  image?: (string | null) | Media;
  /**
   * Optional public or remote image URL used by the homepage card.
   */
  imageUrl?: string | null;
  /**
   * Full URL of the website to embed as a live preview (e.g. https://example.com).
   */
  livePreviewUrl?: string | null;
  href?: string | null;
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: string;
  name: string;
  /**
   * Select or upload the partner logo image
   */
  logo?: (string | null) | Media;
  href?: string | null;
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: string;
  title: string;
  excerpt: string;
  /**
   * Upload or select a blog post cover image.
   */
  image?: (string | null) | Media;
  /**
   * Optional public or remote image URL used by the homepage card.
   */
  imageUrl?: string | null;
  href?: string | null;
  publishedAt?: string | null;
  isFeatured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "statistics".
 */
export interface Statistic {
  id: string;
  value: string;
  label: string;
  description?: string | null;
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'statistics';
        value: string | Statistic;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: string | CaseStudy;
      } | null)
    | ({
        relationTo: 'partners';
        value: string | Partner;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: string | BlogPost;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  hero?:
    | T
    | {
        type?: T;
        badge?: T;
        title?: T;
        subtitle?: T;
        primaryCta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        secondaryCta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        homepageHeadline?:
          | T
          | {
              before?: T;
              emphasis?: T;
              after?: T;
            };
        homepageSubtitle?: T;
        homepagePrimaryCta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        homepageCards?:
          | T
          | {
              title?: T;
              description?: T;
              visual?: T;
              id?: T;
            };
      };
  layout?:
    | T
    | {
        'hero-block'?:
          | T
          | {
              headline?:
                | T
                | {
                    before?: T;
                    emphasis?: T;
                    after?: T;
                  };
              subtitle?: T;
              primaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              cards?:
                | T
                | {
                    title?: T;
                    description?: T;
                    visual?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'services-block'?:
          | T
          | {
              sectionTag?: T;
              title?: T;
              description?: T;
              selectionMode?: T;
              manualServices?: T;
              id?: T;
              blockName?: T;
            };
        'featured-work-block'?:
          | T
          | {
              sectionTag?: T;
              title?: T;
              description?: T;
              selectionMode?: T;
              manualCaseStudies?: T;
              id?: T;
              blockName?: T;
            };
        'partners-block'?:
          | T
          | {
              sectionTag?: T;
              selectionMode?: T;
              manualPartners?: T;
              id?: T;
              blockName?: T;
            };
        'blog-block'?:
          | T
          | {
              sectionTag?: T;
              title?: T;
              description?: T;
              selectionMode?: T;
              manualPosts?: T;
              id?: T;
              blockName?: T;
            };
        'statistics-block'?:
          | T
          | {
              sectionTag?: T;
              title?: T;
              selectionMode?: T;
              manualStats?: T;
              id?: T;
              blockName?: T;
            };
        'methodology-block'?:
          | T
          | {
              sectionTag?: T;
              title?: T;
              steps?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'who-we-are-block'?:
          | T
          | {
              sectionTag?: T;
              title?: T;
              description?: T;
              whyCards?:
                | T
                | {
                    icon?: T;
                    iconMedia?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'final-cta-block'?:
          | T
          | {
              headline?: T;
              subtitle?: T;
              primaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              secondaryCta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'about-hero-block'?:
          | T
          | {
              sectionTag?: T;
              title?: T;
              description?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'about-story-block'?:
          | T
          | {
              sectionTag?: T;
              title?: T;
              description?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        'about-values-block'?:
          | T
          | {
              cards?:
                | T
                | {
                    title?: T;
                    description?: T;
                    bgType?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'solutions-block'?:
          | T
          | {
              sectionTag?: T;
              title?: T;
              items?:
                | T
                | {
                    name?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'sectors-block'?:
          | T
          | {
              sectionTag?: T;
              title?: T;
              sectors?:
                | T
                | {
                    name?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogTitle?: T;
        ogType?: T;
        ogDescription?: T;
        ogImage?: T;
        twitterCard?: T;
        canonicalUrl?: T;
        noIndex?: T;
        noFollow?: T;
        structuredData?: T;
      };
  settings?:
    | T
    | {
        transparentHeader?: T;
        pageTemplate?: T;
        breadcrumbVisibility?: T;
        defaultTheme?: T;
        animationToggle?: T;
        previewImage?: T;
        analyticsIdentifiers?:
          | T
          | {
              gtmId?: T;
              conversionTag?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogTitle?: T;
        ogType?: T;
        ogDescription?: T;
        ogImage?: T;
        twitterCard?: T;
        canonicalUrl?: T;
        noIndex?: T;
        noFollow?: T;
        structuredData?: T;
      };
  slug?: T;
  layout?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "statistics_select".
 */
export interface StatisticsSelect<T extends boolean = true> {
  value?: T;
  label?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  displayMode?: T;
  image?: T;
  imageUrl?: T;
  livePreviewUrl?: T;
  href?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  href?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  image?: T;
  imageUrl?: T;
  href?: T;
  publishedAt?: T;
  isFeatured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  siteName?: string | null;
  brandLogo?: (string | null) | Media;
  contactEmail?: string | null;
  contactPhone?: string | null;
  address?: string | null;
  socialLinks?:
    | {
        platform: string;
        url: string;
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: string;
  brand?: string | null;
  cta?: {
    label?: string | null;
    href?: string | null;
  };
  links?:
    | {
        label: string;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  socialTitle?: string | null;
  socialLinks?:
    | {
        platform: 'facebook' | 'twitter' | 'snapchat' | 'tiktok' | 'instagram';
        url: string;
        id?: string | null;
      }[]
    | null;
  locationTitle?: string | null;
  location?: string | null;
  contactTitle?: string | null;
  email?: string | null;
  phone?: string | null;
  linksTitle?: string | null;
  links?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-content".
 */
export interface HeroContent {
  id: string;
  headline?: {
    before?: string | null;
    emphasis?: string | null;
    after?: string | null;
  };
  subtitle?: string | null;
  primaryCta?: {
    label?: string | null;
    href?: string | null;
  };
  cards?:
    | {
        title: string;
        description: string;
        visual?: ('button' | 'process' | 'chart') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-settings".
 */
export interface HomepageSetting {
  id: string;
  nav?: {
    brand?: string | null;
    cta?: {
      label?: string | null;
      href?: string | null;
    };
    links?:
      | {
          label: string;
          href?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  partners?: {
    eyebrow?: string | null;
    heading?: string | null;
  };
  services?: {
    eyebrow?: string | null;
    heading?: string | null;
  };
  whoWeAre?: {
    heading?: string | null;
    body?: string | null;
    cta?: {
      label?: string | null;
      href?: string | null;
    };
  };
  whyUs?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  results?: {
    eyebrow?: string | null;
    heading?: string | null;
    cta?: {
      label?: string | null;
      href?: string | null;
    };
  };
  methodology?: {
    eyebrow?: string | null;
    heading?: string | null;
    steps?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    cta?: {
      label?: string | null;
      href?: string | null;
    };
  };
  finalCta?: {
    heading?: string | null;
    body?: string | null;
    imageUrl?: string | null;
    cta?: {
      label?: string | null;
      href?: string | null;
    };
  };
  blog?: {
    eyebrow?: string | null;
    heading?: string | null;
  };
  footer?: {
    socialTitle?: string | null;
    locationTitle?: string | null;
    location?: string | null;
    contactTitle?: string | null;
    email?: string | null;
    phone?: string | null;
    copyright?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  brandLogo?: T;
  contactEmail?: T;
  contactPhone?: T;
  address?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        icon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  brand?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  links?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  socialTitle?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  locationTitle?: T;
  location?: T;
  contactTitle?: T;
  email?: T;
  phone?: T;
  linksTitle?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-content_select".
 */
export interface HeroContentSelect<T extends boolean = true> {
  headline?:
    | T
    | {
        before?: T;
        emphasis?: T;
        after?: T;
      };
  subtitle?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  cards?:
    | T
    | {
        title?: T;
        description?: T;
        visual?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-settings_select".
 */
export interface HomepageSettingsSelect<T extends boolean = true> {
  nav?:
    | T
    | {
        brand?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
      };
  partners?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
      };
  services?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
      };
  whoWeAre?:
    | T
    | {
        heading?: T;
        body?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  whyUs?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  results?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  methodology?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        steps?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  finalCta?:
    | T
    | {
        heading?: T;
        body?: T;
        imageUrl?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  blog?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
      };
  footer?:
    | T
    | {
        socialTitle?: T;
        locationTitle?: T;
        location?: T;
        contactTitle?: T;
        email?: T;
        phone?: T;
        copyright?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}